name: DPLobby
main: net.deadpvp.Main
version: 1.0
author: [Benigne, Red_Spash, Arnaud013]
description: Plugin de lobby pour DEADPVP
commands:
  creatif:
    description: Aller sur le serveur créatif
  pvpsoup:
    description: Aller sur le serveur soup
  fixvote:
    description: Commande admin pour fix le pnj
